#!/bin/sh -l

#PBS -N comp_start
#PBS -q beagle
#PBS -l nodes=1:ppn=1,naccesspolicy=singleuser
#PBS -l walltime=336:00:00
#PBS -e compare10.sterror
#PBS -o compare10.stout
#PBS -m abe
#PBS -M jwillou@purdue.edu

cd /scratch/snyder/j/jwillou/wgs/compare #$PBS_O_WORKDIR

#create submission files
count=0
cat notcomplete.txt | while IFS=$'\t' read -r sp1 sp2 class
	do
	count=$((count+1))
	printf '#!/bin/bash\n' > "mum${count}".job
	printf "#PBS -N comp_mum\n" >> "mum${count}".job
	printf "#PBS -q beagle\n" >> "mum${count}".job
	printf "#PBS -l nodes=1:ppn=1,naccesspolicy=singleuser\n" >> "mum${count}".job
	printf "#PBS -l walltime=336:00:00\n" >> "mum${count}".job
	printf "#PBS -e ${sp1}_${sp2}.sterror\n" >> "mum${count}".job
	printf "#PBS -o ${sp1}_${sp2}.stout\n" >> "mum${count}".job
	printf "\n" >> "mum${count}".job
	printf "module load MUMmer/3.23\n" >> "mum${count}".job
	printf "cd /scratch/snyder/j/jwillou/wgs/compare\n" >> "mum${count}".job
	printf "\n" >> "mum${count}".job
	printf "mkdir -p -- ${sp1}_${sp2}\n" >> "mum${count}".job
	printf "cd ${sp1}_${sp2}\n" >> "mum${count}".job
	printf "\n" >> "mum${count}".job
	printf "#run mummer, ref=sp1, query=sp2\n" >> "mum${count}".job
	printf "nucmer --mum --maxgap=500 --mincluster=100 --prefix=sp1_sp2 "../../data/${sp1}/genome.fa" "../../data/${sp2}/genome.fa"\n" >> "mum${count}".job
	printf "show-coords -r sp1_sp2.delta > sp1_sp2.coords\n" >> "mum${count}".job
	printf "show-aligns sp1_sp2.delta refname qryname > sp1_sp2.aligns\n" >> "mum${count}".job
	printf "delta-filter -q -r sp1_sp2.delta > sp1_sp2.delta.filter\n" >> "mum${count}".job
	printf "\n" >> "mum${count}".job
	printf "#run mummer, ref=sp2, query=sp1\n" >> "mum${count}".job
	printf "nucmer --mum --maxgap=500 --mincluster=100 --prefix=sp2_sp1 "../../data/${sp2}/genome.fa" "../../data/${sp1}/genome.fa"\n" >> "mum${count}".job
	printf "show-coords -r sp2_sp1.delta > sp2_sp1.coords\n" >> "mum${count}".job
	printf "show-aligns sp2_sp1.delta refname qryname > sp2_sp1.aligns\n" >> "mum${count}".job
	printf "delta-filter -q -r sp2_sp1.delta > sp2_sp1.delta.filter\n" >> "mum${count}".job	
done

#change permissions
chmod u+x mum*

#get list of files
ls mum* > mum.txt

#submit list
printf "#!/bin/bash\n" > joblist.job
printf "#PBS -N comp_mum\n" >> joblist.job
printf "#PBS -q beagle\n" >> joblist.job
printf "#PBS -l nodes=1:ppn=1,naccesspolicy=singleuser\n" >> joblist.job
printf "#PBS -l walltime=336:00:00\n" >> joblist.job
printf "#PBS -e jlist.sterror\n" >> joblist.job
printf "#PBS -o jlist.stout\n" >> joblist.job
printf "#PBS -m abe\n" >> joblist.job
printf "#PBS -M jwillou@purdue.edu\n" >> joblist.job
printf "cd /scratch/snyder/j/jwillou/wgs/compare\n" >> joblist.job
cat mum.txt | while IFS= read -r LINE
do
	printf "qsub ${LINE}\n" >> joblist.job	
done
qsub joblist.job
rm mum.txt

mkdir mummerscripts
mv mum* mummerscripts/

