#!/bin/bash

#PBS -N fixfasta
#PBS -q darwin
#PBS -l nodes=1:ppn=2,naccesspolicy=singleuser
#PBS -l walltime=336:00:00
#PBS -m abe
#PBS -M jwillou@purdue.edu

cd /scratch/snyder/j/jwillou/wgs/data #$PBS_O_WORKDIR

cat specieslist.txt | while IFS= read -r LINE
	do
	cd $LINE
	perl ../../convert_fastamulti.pl
	awk 'BEGIN{FS=" "}{if(!/>/){print toupper($0)}else{print $1}}' genome_format.fa > genome_format_unmask.fa
	wait
	cd ../
done
